name: dev-proxy

# define named network for use in other projects
networks:
  default:
    name: dev_proxy

services:
  # central proxy serving index page and forwarding requests to upstream services
  nginx:
    container_name: dev_proxy
    image: nginx:stable
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.generated/html:/usr/share/nginx/html
      - ./.generated/certs:/etc/nginx/certs
      - ./.generated/config/:/etc/nginx/conf.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # watches container events, generates certificates, updates index page and nginx config
  docker-gen:
    build:
      context: .docker/docker-gen
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - nginx
    tty: true
    command: -config /etc/docker-gen/config
    environment:
      CAROOT: /etc/nginx/certs

  # provides smtp server and web interface to test emails locally
  maildev:
    container_name: maildev
    image: maildev/maildev:latest
    restart: unless-stopped
    environment:
      MAILDEV_IP: "::" # fixes issue with healthcheck (see https://github.com/maildev/maildev/issues/484#issuecomment-2167374618)
      VIRTUAL_HOST: maildev.localhost
      VIRTUAL_PORT: 1080